apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP  # Use ClusterIP for internal communication
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # Expose the frontend service externally
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend