name: Push Backend Docker image to AWS ECR Repo

on:
  push:
    branches: [ "main" ]
    #paths:
    #  - backend/**
  pull_request:
    branches: [ "main" ]
    #paths:
    #  - backend/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build Backend Docker image
      run: docker build ./backend -t cosierra/backend:$(date +%s)
