name: Push Frontend Docker image to AWS ECR Repo

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION}}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN}}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and tag the docker 
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.FRONTEND_REPO_NAME }}
      run: docker build ./frontend/front-pymes -t $ECR_REGISTRY/$ECR_REPOSITORY

    - name: Push image to Amazon ECR
      id: push-image 
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.FRONTEND_REPO_NAME }}
      run: docker push $ECR_REGISTRY/$ECR_REPOSITORY
        
